drainet:
  - title: 大屏
    name: components
    type: components
    groups:
      - title: page
        name: page
        items:
          - title: test1
            name: test1
          - title: test2
            name: test2
          - title: test3
            name: test3
          - title: test4
            name: test4
          - title: test5
            name: test5
          - title: 页面组件
            name: page
            pages:
              - title: 排水户
                name: sewagelist
          - title: 净水站
            name: water
            pages:
              - title: 净水站列表
                name: waterStation
              - title: 净水站底部
                name: waterStationBot
              - title: 净水站左侧
                name: waterStationLeft
              - title: 净水站右侧
                name: waterStationRight
